import { NextResponse } from "next/server";
import { db } from "../../../../lib/db";
import { currentUser } from "../../../../lib/auth";
import { slugify } from "../../../../lib/articles";
export const dynamic = "force-dynamic";
export async function GET(){if(!await currentUser())return NextResponse.json({error:"Unauthorized"},{status:401});return NextResponse.json(db.prepare("SELECT * FROM articles ORDER BY id DESC").all());}
export async function POST(req:Request){const user=await currentUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});const a=await req.json();const now=new Date().toISOString();const slug=slugify(a.slug||a.title);const result=db.prepare("INSERT INTO articles(slug,title,abstract,body,keywords,image_url,image_width,image_height,category,status,author_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").run(slug,a.title,a.abstract||"",a.body||"",a.keywords||"",a.imageUrl||"",a.imageWidth||0,a.imageHeight||0,a.category||"News",a.status||"draft",user,now,now);return NextResponse.json({id:result.lastInsertRowid,slug});}
export async function PUT(req:Request){if(!await currentUser())return NextResponse.json({error:"Unauthorized"},{status:401});const a=await req.json();if(!a.id)return NextResponse.json({error:"id required"},{status:400});const now=new Date().toISOString();db.prepare("UPDATE articles SET title=?,abstract=?,body=?,keywords=?,image_url=?,image_width=?,image_height=?,category=?,status=?,updated_at=? WHERE id=?").run(a.title,a.abstract||"",a.body||"",a.keywords||"",a.imageUrl||"",a.imageWidth||0,a.imageHeight||0,a.category||"News",a.status||"draft",now,a.id);return NextResponse.json({ok:true});}
export async function DELETE(req:Request){if(!await currentUser())return NextResponse.json({error:"Unauthorized"},{status:401});const id=new URL(req.url).searchParams.get("id");if(!id)return NextResponse.json({error:"id required"},{status:400});db.prepare("UPDATE articles SET status='archived',updated_at=? WHERE id=?").run(new Date().toISOString(),id);return NextResponse.json({ok:true});}
